[build]
builder = "nixpacks"
buildCommand = "cd backend && go mod download && go build -o main ."

[deploy]
startCommand = "cd backend && ./main"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[healthcheck]
path = "/health"
port = 5050  # Pastikan sama dengan di main.go
timeout = 30
interval = 15
initialDelay = 5

[[services]]
name = "web"
httpPort = 5050  # Pastikan sama dengan di main.go