[build]
builder = "nixpacks"
buildCommand = "cd backend && go build -o main ."

[deploy]
startCommand = "cd backend && ./main"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[healthcheck]
path = "/health"
port = 8080
timeout = 30
interval = 15
initialDelay = 5