[build]
builder = "nixpacks"
buildCommand = "go build -o main ./backend"
ignoreDockerfile = true

[deploy] 
startCommand = "./main"

[healthcheck]
path = "/health"
port = 5050

# Force nixpacks to ignore Dockerfile completely
[nixpacks]
disableDockerfile = true  #