[build]
builder = "nixpacks"
buildCommand = "go build -o main ."

[deploy]
startCommand = "./main"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[healthcheck]
path = "/health"
port = 5050
timeout = 30
interval = 15
initialDelay = 5

[[services]]
name = "web"
httpPort = 5050